# Generated by Django 4.1.3 on 2022-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0002_rename_bisiness_books_book_business_books_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_book", models.CharField(max_length=100)),
            ],
        ),
    ]
