# Generated by Django 4.1.3 on 2022-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0003_booksearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="availability",
            field=models.BooleanField(default=False),
        ),
    ]
