# Generated by Django 4.1.3 on 2022-11-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0004_book_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="availability", new_name="unavailable",
        ),
    ]
