# Generated by Django 4.1.3 on 2022-11-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_rename_availability_book_unavailable"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="unavailable",),
        migrations.AddField(
            model_name="book", name="stock", field=models.IntegerField(default=1),
        ),
    ]
