# Generated by Django 4.1.3 on 2022-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0006_remove_book_unavailable_book_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="stock", field=models.IntegerField(default=1),
        ),
    ]
