# Generated by Django 4.1.3 on 2022-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0007_alter_book_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="stock", field=models.IntegerField(),
        ),
    ]
