# Generated by Django 4.1.3 on 2022-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0008_alter_book_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="stock", field=models.CharField(max_length=50),
        ),
    ]
