# Generated by Django 4.1.3 on 2022-11-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0009_alter_book_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="stock", new_name="avilability",
        ),
    ]
