# Generated by Django 4.1.3 on 2022-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0010_rename_stock_book_avilability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="avilability", field=models.IntegerField(default=1),
        ),
    ]
