# Generated by Django 4.1.3 on 2022-11-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0012_remove_book_avilability_book_stock_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="book", table=None,),
    ]
