# Generated by Django 4.1.3 on 2022-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0013_alter_book_table"),
    ]

    operations = [
        migrations.RenameField(model_name="book", old_name="stock", new_name="juli",),
    ]
