# Generated by Django 4.1.3 on 2022-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0015_remove_book_juli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="stock", field=models.IntegerField(default=0),
        ),
    ]
